ADEVICE pulse:direwolf_tx.monitor pulse:direwolf_tx
ARATE 48000
CHANNEL 0
MYCALL N0CALL-1
MODEM 1200
KISSPORT 8001

ADEVICE1 pulse:direwolf_rx.monitor pulse:direwolf_rx
ARATE 48000
CHANNEL 2
MYCALL N0CALL-1
MODEM 1200
